
DROP TABLE PAYMENT_TYPE ;

CREATE TABLE PAYMENT_TYPE (
    ID SERIAL PRIMARY KEY,
    PAYMENT_MODE VARCHAR( 20 ) NOT NULL,
    PAYMENT_MODE_DETAIL VARCHAR( 80 )
);

DROP TABLE EXPENSE_CATEGORY ;

CREATE TABLE EXPENSE_CATEGORY (
    ID SERIAL PRIMARY KEY,
    EXPENSE_TYPE VARCHAR( 40 ),
    EXPENSE_TYPE_DETAIL VARCHAR( 80 )
);

DROP TABLE PERSON ;

CREATE TABLE PERSON (
    ID SERIAL PRIMARY KEY,
    PERSON_FIRST_NAME VARCHAR( 100 ) NOT NULL,
    PERSON_LAST_NAME VARCHAR( 100 ) NOT NULL,
    PERSON_SHORT_NAME VARCHAR( 50 ) NOT NULL
);

DROP TABLE STORE ;

CREATE TABLE STORE (
    ID SERIAL PRIMARY KEY,
    STORE_NAME VARCHAR( 40 ) NOT NULL,
    STORE_DETAIL VARCHAR( 100 ),
    HOME_DELIVERY VARCHAR( 1 )
);


DROP TABLE EXPENSE ;

CREATE TABLE EXPENSE (
    ID SERIAL PRIMARY KEY,
    EXPENSE_DETAIL VARCHAR(60),
    EXPENSE_CATEGORY_ID INTEGER REFERENCES EXPENSE_CATEGORY( ID ),
    EXPENSE_DATE DATE ,
    EXPENSE_AMOUNT NUMERIC(10,3),
    PAYMENT_TYPE_ID INTEGER REFERENCES PAYMENT_TYPE( ID ),
    PERSON_ID INTEGER REFERENCES PERSON( ID ),
    STORE_ID INTEGER REFERENCES STORE( ID )
);

CREATE TABLE LOGIN (
    LOGIN_ID        VARCHAR( 75 ) NOT NULL,
    PASSWORD_HASH   VARCHAR( 256 ) NOT NULL,
    ACTIVE          VARCHAR( 1 )
);




